
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
# composer Service Job
  composer-service:
    name: composer Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for composer Service
        run: docker build -t cr-composer .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push composer Service to Docker Hub
        run: |
          docker tag cr-composer ${{ secrets.DOCKER_USERNAME }}/cr-composer:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cr-composer:latest